# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180815_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='github_link',
            new_name='github',
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
